project_id = "pwkczhxdgivypgoxpbjz"

[functions.ml-auth]
verify_jwt = true

[functions.ml-config]
verify_jwt = false

[functions.ml-callback]
verify_jwt = false

[functions.test-ml-credentials]
verify_jwt = false