// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwkczhxdgivypgoxpbjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a2N6aHhkZ2l2eXBnb3hwYmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDkwODIsImV4cCI6MjA3MDc4NTA4Mn0.m08tg0s00GIis8-C_XQ1erm83Z2STa2gg0vEkbcXUDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});